export const START_MORNING_SESSION = 1;
export const END_MORNING_SESSION = 6;
export const START_AFTERNOON_SESSION = 7;
export const END_AFTERNOON_SESSION = 12;
export const START_EVENING_SESSION = 13;
export const END_EVENING_SESSION = 16;
